#!/bin/bash

c64_config="
[colors]
foreground=0088ff
background=0000aa"
mz_config="
[colors]
foreground=ffffff
background=0000ff"
msg='cowsay this is just a terminal'

foot -c <(echo "${c64_config}") -f "C64_C64_UP\-1_P:size=12" bash -c \
  "clear; cat c64_boot.txt; read" &
foot -c <(echo "${c64_config}") -f "C64_C64_UP\-1_P:size=12" bash -c \
  "clear; cat c64_boot.txt; echo; echo $ ${msg}; ${msg}; echo -n '$ '; read" &
foot -c <(echo "${mz_config}") -f "SharpMZ_P:size=12" bash -c \
  "clear; cat sharpmz_boot.txt; read" &
