#!/bin/bash

foot -f "MSX_charset_international:size=12.5" bash -c \
  "clear; cat msx_normal.txt; read" &
foot -f "MSX_charset_international_P:size=12" bash -c \
  "clear; cat msx_primary.txt; read" &
foot -f "MSX_charset_international:size=11" bash -c \
  "clear; retrofont show 0; read" &
foot -f "test_font:size=16" bash -c \
  "clear; cat test_font.txt; read" &
