[build-system]
requires = ['hatchling']
build-backend = 'hatchling.build'

[project]
name = 'RetroFont'
description = 'TrueType retro fonts.'
version = '1.0.0'

authors = [{name = 'Jeroen F.J. Laros', email = 'jlaros@fixedpoint.nl'}]
urls = {homepage = 'https://github.com/jfjlaros/retrofont'}
readme = 'README.rst'
keywords = ['retro', 'font', 'TrueType']
classifiers = [
    'Programming Language :: Python :: 3',
    'Operating System :: OS Independent']
license = 'MIT'

dependencies = ['fonttools', 'pyyaml']

[project.scripts]
retrofont = 'retrofont:cli.main'
