[build-system]
requires = ['hatchling', 'pyyaml']
build-backend = 'hatchling.build'

[project]
name = 'retrofont'
dynamic = [
  'authors', 'classifiers', 'description', 'keywords', 'license',
  'license-files', 'version']
readme = 'README.rst'

[project.scripts]
retrofont = 'retrofont:cli.main'

[tool.hatch.metadata.hooks.custom]
path = 'retrofont/meta.py'
